# Bitbucket Pipeline configuration

# Uses black and flake8 to check code style

image: python:3.10

pipelines:
  default:
    - parallel:
        - step:
            name: Check code format
            script:
              - pip install black
              - black -l 79 --check .
        - step:
            name: Lint code
            script:
              - pip install flake8
              - flake8 --extend-exclude=dist,build --show-source --statistics --extend-ignore=E203 .
