[project]
name = "budg"
version = "1.0.0"
description = "a simple budget tool"
authors = ["Kyle Bouwman <kyle@kybouw.com>"]
license = "GPLv3"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "tomli>=2.0.2",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]
